title: Kris Syevens # your name (or website title) here
logo: "/images/profile-pic-cir.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Kris! 
  <br><br>
   I use software development to transform my business, analytical, finance skills into real world problem solving solutions. 
  <br><br>
  <a href="https://www.linkedin.com/in/syevens/">LinkedIn</a> 
  <br>
  <a href="https://github.com/Kris-Syevens/">GitHub</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
